"""empty message

Revision ID: b872216924e4
Revises: 
Create Date: 2021-10-03 04:00:08.307238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b872216924e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abe_hiroshi_books',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('book_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abe_hiroshi_books')
    # ### end Alembic commands ###
